services:
  webapp:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app_net
    depends_on:
      - backend
    environment:
      FRONTEND_API_URL: ${FRONTEND_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./api
    ports:
      - "${API_PORT}:5000"
    networks:
      - app_net
    depends_on:
      - database
      - auditlog
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      LOGGING_URL: ${LOGGING_URL}
      SERVICE_NAME: backend
    volumes:
      - ./api:/app
      - /app/node_modules

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app_net
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./api/core/dbInitializer.sql:/docker-entrypoint-initdb.d/dbInitializer.sql

  auditlog:
    build: ./logger
    ports:
      - "${LOGGER_PORT}:4000"
    networks:
      - app_net
    environment:
      LOGGER_PORT: ${LOGGER_PORT}
    volumes:
      - ./logger:/app
      - /app/node_modules
      - ./logger/logs:/app/logs

networks:
  app_net:

volumes:
  pgdata:
